app/comments/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import DataRequired

class commentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[DataRequired("Please enter a comment")])

app/comments/__init__.py
from flask import Blueprint

comments = Blueprint('comments', __name__)

from . import views

app/comments/views.py
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from . import comments
from .. models import Campground, Comment, User
from decorators import check_confirmed
from . forms import commentForm
from app import db

@comments.route('/add', methods=['GET', 'POST'])
@login_required
@check_confirmed
def add_comment(slug, campground_id):
    """
    Handles comment creation at /campgrounds/campground_id>/<slug>/comment/add
    Associate a particular comment with the user that created the comment
    as well as the campground for which the comment was was created.

    redirect to /campground/<slug/campground_id

    """
    add_comment = True
    campground = Campground.query.get_or_404(campground_id)
    user = User.query.get_or_404(current_user.id)
    comment_form = commentForm()
    if comment_form.validate_on_submit():
        comment = Comment(comment=comment_form.comment.data,
                         user_comment=user,
                         campground_comment=campground)
        db.session.add(comment)
        db.session.commit()
        flash('Comment for {} successfully added'.format(campground.name), 'success')
        return redirect(url_for('campground.display_campground', slug=campground.slugified_name, campground_id=campground.id ))


    return render_template('comments/create_comment.html', comment_form=comment_form, campground=campground, add_comment=add_comment, title='Create Comment')

@comments.route('/<int:comment_id>/edit', methods=['GET', 'POST'])
@login_required
@check_confirmed
def edit_comment(slug, campground_id, comment_id):
    """
    Handles editing of a user comment at route /campgrounds/campground_id>/<slug>/comment/comment_id/edit

    """
    add_comment = False
    campground = Campground.query.get_or_404(campground_id)
    comment = Comment.query.get_or_404(comment_id)
    comment_form = commentForm(obj=comment)
    if comment_form.validate_on_submit():
        comment.comment = comment_form.comment.data
        db.session.commit()
        return redirect(url_for('campground.display_campground', slug=campground.slugified_name, campground_id=campground.id))

    return render_template('comments/create_comment.html', campground=campground, comment_form=comment_form, comment=comment, add_comment=add_comment, title="Edit Comment")

@comments.route('/<int:comment_id>/delete', methods=['GET', 'POST'])
@login_required
@check_confirmed
def delete_comment(slug, campground_id, comment_id):
    """
    Handles campground deletion at /campgrounds/campground_id>/<slug>/comment/comment_id/delete
    """
    campground = Campground.query.get_or_404(campground_id)
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('campground.display_campground', slug=campground.slugified_name, campground_id=campground.id))

app/templates/comments/create_comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
    <div class="col-md-6 mx-auto mt-4">
    {% if add_comment %}
    <h4 class='text-center'>Add a comment for {{campground.name }}</h4>
    <form action="{{url_for('comments.add_comment', slug=campground.slugified_name, campground_id=campground.id)}}" method='POST'>
    {% else %}
    <h4 class='text-center'>Edit a comment for {{campground.name }}</h4>
     <form action="{{url_for('comments.edit_comment', slug=campground.slugified_name, campground_id=campground.id, comment_id=comment.id)}}" method='POST'>
         {% endif %}
        {{comment_form.hidden_tag()}}
        {% if comment_form.comment.errors %}
           {% for error in comment_form.comment.errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <strong>{{error}}</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
           
        {% endfor %}
        {% endif %}
         <div class="form-group">
             {{comment_form.comment.label}}
             {{comment_form.comment(class="form-control form-control-md", id="comment", placeholder="Enter Comment", rows="7")}}
          </div>
          {% if add_comment %}
          <button type="submit" class="btn btn-primary">Add comment</button>
          {% else %}
          <button type="submit" class="btn btn-primary">Edit Comment</button>
          {% endif %}
          <a class="btn btn-primary" href="{{url_for('campground.display_campground', campground_id=campground.id, slug=campground.slugified_name)}}">Cancel</a>
        </form>
        </div>
    </div>
</div>
{% endblock %}