app/campgrounds/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField,TextAreaField, ValidationError
from wtforms.validators import DataRequired

from flask_wtf.file import FileField, FileAllowed, FileRequired

class CampgroundForm(FlaskForm):
    """
    form for a users to add campgrounds
    """
    name = StringField('Campground name', validators=[DataRequired('Please enter campground name')])
    image = FileField('image', validators=[DataRequired('Please upload an image'),FileAllowed(['jpg', 'png', 'jpeg'], 'image must be a jpg, png or jpeg')])
    location = StringField('Location', validators=[DataRequired('Please enter a location')])
    price = StringField('Price', validators=[DataRequired('Please enter Price')])
    description = TextAreaField('Description', validators=[DataRequired('Please enter descriptoin of campground')])

    

app/campgrounds/__init__.py
from flask import Blueprint

campground = Blueprint('campground', __name__)

from . import views

app/campgrounds/views.py
from flask import flash, redirect, render_template, url_for, request
from flask_login import login_required, login_user, logout_user, current_user, login_manager
from decorators import check_confirmed
import geocoder
from cloudinary.uploader import upload, destroy
from cloudinary.utils import cloudinary_url
from app import create_app
from .. models import Campground, Comment, User
from app import db
from . import campground
from . forms import CampgroundForm

@campground.route('/')
def list_all_campgrounds():
    """
    Show all campgrounds at route /campgrounds/
    """
    campgrounds = Campground.query.all()
    return render_template('campgrounds/list_campgrounds.html', campgrounds=campgrounds, title="Campgrounds")

@campground.route('/add', methods=['GET','POST'])
@login_required
@check_confirmed
def create_campground():
    add_campground = True
    image_url = None
    image_id = None
    user = User.query.get(current_user.id)
    campground_form = CampgroundForm()
    if campground_form.validate_on_submit():
            campground = Campground(name=campground_form.name.data,
                        price=campground_form.price.data,
                        description=campground_form.description.data,
                        user_campground=user)
            g = geocoder.google(campground_form.location.data)
            address = g.json
            if address is None:
                flash('The address you entered isn\'t correct', 'danger')
                return redirect(url_for('campground.create_campground'))
            campground.location = g.json.get('raw').get('formatted_address')
            campground.lat= g.json.get('raw').get('geometry').get('location').get('lat')
            campground.lng = g.json.get('raw').get('geometry').get('location').get('lng')
            file_to_upload = request.files['image']
            if file_to_upload:
                upload_result = upload(file_to_upload)
                image_url = upload_result.get('secure_url')
                image_id = upload_result.get('public_id')
            campground.image = image_url
            campground.image_id = image_id
            db.session.add(campground)
            db.session.commit()
            return redirect(url_for('campground.list_all_campgrounds'))

    return render_template('campgrounds/campground.html', campground_form=campground_form, add_campground=add_campground, title="New Campground")

@campground.route('/<int:campground_id>/<slug>')
def display_campground(campground_id, slug):
    """
    Show a particular campground at route /campgrounds/campground_id/<slug>
    """
    campground = Campground.query.get_or_404(campground_id)
    return render_template('campgrounds/show_campground.html', campground=campground, title=campground.name)

@campground.route('/<int:campground_id>/<slug>/edit', methods=['GET', 'POST'])
@login_required
@check_confirmed
def edit_campground(campground_id, slug):
    """
    Edit a campground at route /campgrounds/campground_id/<slug>/edit
    """
    add_campground = False
    image_url = None
    image_id = None
    campground = Campground.query.get_or_404(campground_id)
    campground_form = CampgroundForm(obj=campground)
    if campground_form.validate_on_submit():
        campground.name = campground_form.name.data
        campground.image = campground_form.image.data
        campground.price = campground_form.price.data
        campground.description = campground_form.description.data
        g = geocoder.google(campground_form.location.data)
        address = g.json
        if address is None:
            flash('The address you entered isn\'t correct', 'danger')
            return redirect(url_for('campground.edit_campground', slug=campground.slugified_name, campground_id=campground.id))
        campground.location = g.json.get('raw').get('formatted_address')
        campground.lat= g.json.get('raw').get('geometry').get('location').get('lat')
        campground.lng = g.json.get('raw').get('geometry').get('location').get('lng')
        file_to_upload = request.files.get('image')
        if file_to_upload:
            destroy(campground.image_id)
            upload_result = upload(file_to_upload)
            image_url = upload_result.get('secure_url')
            image_id = upload_result.get('public_id')
            campground.image = image_url
            campground.image_id = image_id
        db.session.commit()
        return redirect(url_for('campground.display_campground', campground_id=campground.id, slug=campground.slugified_name))

    return render_template('campgrounds/campground.html', campground_form=campground_form, add_campground=add_campground, campground=campground)

@campground.route('/<int:campground_id>/<slug>/delete', methods=['GET','POST'])
@login_required
@check_confirmed
def delete_campground(campground_id, slug):
    """
    Delete a campground at route /campgrounds/campground_id/<slug>/delete
    """
    campground = Campground.query.get_or_404(campground_id)
    campground_name = campground.name
    destroy(campground.image_id)
    db.session.delete(campground)
    db.session.commit()
    flash(campground_name + ' has been successfully deleted', 'success')
    return redirect(url_for('campground.list_all_campgrounds'))

app/templates/campgrounds/campground.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-md-7 mx-auto">
            {% if add_campground %}
        <form action="{{url_for('campground.create_campground')}}" enctype="multipart/form-data" method="POST">
            {% else %}
        <form action="{{url_for('campground.edit_campground', campground_id=campground.id, slug=campground.slugified_name)}}" enctype="multipart/form-data" method="POST">
            {% endif %}
             {{campground_form.hidden_tag()}}
               {% if campground_form.name.errors %}
               {% for error in campground_form.name.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>{{error}}</strong>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            {% endfor %}
            {% endif %}
             <div class="form-group">
                 {{campground_form.name.label}}
                 {{campground_form.name(class="form-control form-control-md", id="name", placeholder="Enter campground name")}}
              </div>

            {% if campground_form.image.errors %}
               {% for error in campground_form.image.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>{{error}}</strong>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            {% endfor %}
            {% endif %}
             <div class="form-group">
                 {{campground_form.image.label}}
                 {{campground_form.image(class="form-control form-control-md", id="image", placeholder="Enter image url")}}
              </div>

            {% if campground_form.location.errors %}
               {% for error in campground_form.location.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>{{error}}</strong>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            {% endfor %}
            {% endif %}
             <div class="form-group">
                 {{campground_form.location.label}}
                 {{campground_form.location(class="form-control form-control-md", id="location", placeholder="1723 E Panama Dr., CO")}}
              </div>

          {% if campground_form.price.errors %}
               {% for error in campground_form.price.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>{{error}}</strong>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            {% endfor %}
            {% endif %}
             <div class="form-group">
                 {{campground_form.price.label}}
                 {{campground_form.price(class="form-control form-control-md", id="price", type="Number", min="0.01", step="0.01", placeholder="0.00")}}
              </div>

            {% if campground_form.description.errors %}
               {% for error in campground_form.description.errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>{{error}}</strong>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>

            {% endfor %}
            {% endif %}
             <div class="form-group">
                 {{campground_form.description.label}}
                 {{campground_form.description(class="form-control form-control-md", id="description", placeholder="Enter description", rows="7")}}
              </div>
              {% if add_campground %}
                  <button type="submit" class="btn btn-primary">Add campground</button>
             {% else %}
              <button type="submit" class="btn btn-primary">Save changes</button>
              {% endif %}
        </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/campgrounds/list_campgrounds.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
{% if current_user.is_authenticated %}
  <h1 class="display-5 text-center">Hi {{current_user.first_name }}, welcome to Yelp Camp</h1>
  <p class="lead text-center">At Yelp Camp, we are interested in seeing our members share their camping experiences with each other..</p>
  <hr class="my-4">
  <p>You can use the buttons below to either add a campground or go back to home page.</p>
  <a class="btn btn-primary btn-md" href="{{url_for('home.home_page')}}" role="button">Home</a>
  <a class="btn btn-primary btn-md" href="{{url_for('campground.create_campground')}}" role="button">Add a campground</a>
</div>
{% else %}
 <h1 class="display-5 text-center">Hi {{current_user.first_name }}, welcome to Yelp Camp</h1>
  <p class="lead text-center">At Yelp Camp, we are interested in seeing our members share their camping experiences with each other..</p>
  <hr class="my-4">
  <p>You can use the buttons below to either add a campground or go back to home page.</p>
  <a class="btn btn-primary btn-md" href="{{url_for('home.home_page')}}" role="button">Home</a>
  <a class="btn btn-primary btn-md" href="{{url_for('campground.create_campground')}}" role="button">Add a campground</a>
</div>
{% endif %}

<div class="container">
    <div class="row">
        {% if campgrounds %}
           {% for campground in campgrounds %}
            <div class="col-md-4">
            <figure class="figure img-thumbnail">
              <img src="{{campground.image}}" class="figure-img img-fluid " alt="An image of a campground.">
              <figcaption class="figure-caption text-right">{{campground.name}} <a class="btn btn-primary btn-sm" href="{{url_for('campground.display_campground', campground_id=campground.id, slug=campground.slugified_name)}}" role="button">view more...</a></figcaption>
            </figure>
            </div>
            {% endfor %}
          {% else %}
          <h4>No campgrounds have been added</h4>
          {% endif %}
    </div>
</div>
{% endblock %}

app/templates/campgrounds/show_campground.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3 mt-3">
             <p class="lead text-center">Yelp Camp<p>
            <ul class="list-group">
              <li class="list-group-item active">Info 1</li>
              <li class="list-group-item">Info 2</li>
              <li class="list-group-item">Info 3</li>
              <li class="list-group-item">Info 4</li>
         </ul>
         <div id="map" class="mt-2"></div>
            </div>
            <div class="col-md-9 mt-3">
            <div class="card">
              <img class="card-img-top" src="{{campground.image}}" alt="A campground image">
              <div class="card-body">
                  <h4 class=" float-right">{{ "${:,.2f}".format(campground.price) }}/Night</h4>
                  <a href=""><h4 class="text-primary font-bold pb-0 campground-name">{{campground.name}}</h4></a>
                <p class="card-text text-justify mb-0 campground-description">{{campground.description}}</p>
                <span id="lng">{{campground.lng}}</span>
                <span id="lat">{{campground.lat}}</span>
                <span id="loc">{{campground.location}}</span>
              </div>
              <p class="ml-4 text-primary">Submitted By: {{campground.user_campground.first_name}} {{campground.user_campground.last_name}} {{ moment(campground.create_at).fromNow(refresh=True)}}</p>
              {% if campground.user_campground.username == current_user.username %}
              <div class="mb-0 ml-4">
                <a href="{{url_for('campground.edit_campground', campground_id=campground.id, slug=campground.slugified_name)}}" class="btn btn-warning">Edit <ion-icon size="medium" name="create"></ion-icon></a>
             <a href="{{url_for('campground.delete_campground', campground_id=campground.id, slug=campground.slugified_name)}}" class="btn btn-danger text-dark">Delete <ion-icon name="close"></ion-icon></a>
             <p class="float-right mr-4 font-weight-bold text-muted">{{campground.comment.count()}} comment{{campground.comment.count()|pluralize}}</p>
            </div>
            {% endif %}`

            </div>
            <div class="card card-header mt-3">
                <div class="">
                    <a href="{{url_for('comments.add_comment', slug=campground.slugified_name, campground_id=campground.id)}}" class="btn btn-success float-right" style="display:inline">Leave a comment</a>
                </div>
                <hr/>

              {% if campground.comment %}
              {% for comment in campground.comment|sort(attribute='create_at', reverse=True) %}
            <div class="row">
               <div class="col-md-12">
                  <span class="float-right text-muted">{{ moment(comment.create_at).fromNow(refresh=True)}}</span>
                  <p class="font-weight-bold text-muted">{{comment.user_comment.first_name}} {{comment.user_comment.last_name}}</p>
                  <p class="text-justify">{{comment.comment}}</p>
                  {% if comment.user_comment.username == current_user.username %}
                  <div class=" mb-3">
                       <a  href="{{url_for('comments.edit_comment', campground_id=campground.id, comment_id=comment.id, slug=campground.slugified_name)}}" class="btn btn-warning" style="display:inline">Edit <ion-icon size="medium" name="create"></ion-icon></a>
                       <a  href="{{url_for('comments.delete_comment', campground_id=campground.id, comment_id=comment.id, slug=campground.slugified_name)}}" class="btn btn-danger text-dark" style="display:inline">Delete <ion-icon name="close"></ion-icon></a>
                  </div>
                  {% endif %}

               </div>

            </div>
            <hr/>
            {% endfor %}
            {% endif %}
            </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block mapcontent %}
<script src="{{url_for('static', filename='js/googlemap.js')}}"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyArqBRe-0nSAMl-ZOeBinb1SJsGgyltGJY&callback=initMap"></script>

{%endblock %}